project:
  type: book

book:
  title: "R for Research"
  author: "Olamide M. Adu"
  date: "9/5/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - r-rstudio.qmd
    - basics.qmd
    #- intro-github.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: yeti
    cover-image: cover.png
    

  pdf:
    documentclass: scrreprt
    pdf-engine: pdfroff
    cover-image: cover.png
    output-file: pdf-book

editor: visual

