project:
  type: book

book:
  title: "R for Research"
  author: "Olamide M. Adu"
  date: "2024-09-11"
  chapters:
    - index.qmd
    - intro.qmd
    - part: the-basics.qmd
      chapters:
        - r-rstudio.qmd
        - operators.qmd
        - data-types.qmd
        - fns.qmd
        - data-structure.qmd
        - packages.qmd
        - workflow.qmd
    - part: wrangle.qmd
      chapters: 
        - importing-data.qmd
        - data-manip.qmd
    - part: eda.qmd
      chapters: 
        - viz-basic.qmd
        - edaI.qmd
        - edaII.qmd
    - part: com-col.qmd
      chpaters:
        - intro-github.qmd
        - quarto.qmd
    - references.qmd
    
  favicon: cover.png
  cover-image: cover.png
  reader-mode: true
  page-footer:
    left: |
      R for Research was written by Olamide M. Adu.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  site-url: https://r4r.olamideadu.com/
  repo-url: https://github.com/xrander/r4r/
  repo-branch: main

bibliography: references.bib

format:
  html:
    theme: yeti
    cover-image: cover.png
    toc: true
    toc-depth: 3
    code-link: true
    callout-appearance: simple
    page-layout: full
    
  pdf:
    documentclass: scrreprt
    pdf-engine: xelatex
    cover-image: cover.png
    output-file: r-for-research.pdf

editor: source

