project:
  type: book

book:
  title: "R for Research"
  
  date: "2024-09-11"
  favicon: cover.png
  cover-image: cover1.png
  reader-mode: true
  page-footer:
    left: |
      R for Research was written by Olamide M. Adu for yourStudyAssist.
    right: |
      <p>This book was built with <a href="https://quarto.org/">Quarto</a> &commat; 2025</p> .
  site-url: https://r4r.olamideadu.com/
  repo-url: https://github.com/xrander/r4r/
  repo-branch: main
  chapters:
    - index.qmd
    - preface.qmd
    - intro.qmd
    - part: the-basics.qmd
      chapters:
        - r-rstudio.qmd
        - operators.qmd
        - data-types.qmd
        - fns.qmd
        - data-structure.qmd
        - control-str.qmd
        - packages.qmd
        - workflow.qmd
    - part: wrangle.qmd
      chapters: 
        - r-and-research.qmd
        - importing-data.qmd
        - data-manip.qmd
    - part: eda.qmd
      chapters: 
        - viz-basic.qmd
        - edaI.qmd
        - edaII.qmd
    - part: com-col.qmd
      chpaters:
        - intro-github.qmd
        - quarto.qmd
    - references.qmd
  
  

bibliography: references.bib

format:
  html:
    theme: yeti
    cover-image: cover1.png
    toc: true
    toc-depth: 3
    code-link: true
    callout-appearance: simple
    number-sections: true
    title-prefix: "Chapter "
    page-layout: full
    
    author-meta: "Olamide M. Adu"
    
  pdf:
    documentclass: scrreprt
    pdf-engine: xelatex
    cover-image: cover1.png
    output-file: r-for-research.pdf
  

editor: source

