name: Quarto Blog Auto-Render and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches: main
  
  workflow_dispatch:
  schedule:
    - cron: "0 08 * * *"

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.5.57"
          # LaTeX installation
          tinytex: true

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install necessary R packages
        run: |
          Rscript -e 'install.packages(c("quarto", "car", "tidyverse", "psych", "janitor", "stats4nr", "ggthemes", "TukeyC"))'

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.5.57"  # Replace with the latest stable version of Quarto

      - name: Render Quarto site
        run: quarto render

      - name: Push rendered site to deployment branch
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add _book
          git commit -m "Automated site render"
          git push origin main
