name: Quarto Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.5.57"

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Render book
        run: |
          quarto render
          
      - name: Deploy rendered files to Netlify branch
        run: |
          git config -- user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add _book
          git commit -m "Automated book render"
          git push origin main
